# Generated by Django 5.2.8 on 2025-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
    ]
